# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b9854967f7e1e578840ab6b81dde9f7759d941965581881fe8251ee3c0a1460cd2d7f65a158bfdd79773b04812aaab989bdfbed7f535d09087ef564542eb5b

test:
  secret_key_base: 6bae15c52949ad12ed08410e6df8b112b34ccfad1743092260c6f1d6c215fed36e2968120046038bc6abc780ee0bf75b59f2b0db6cd14c6a4f20d9b330044e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
